site_name: Bill Powell Is Alive
site_url: http://billpowellisalive.com
theme:
    name: readthedocs
    custom_dir: custom_theme
    include_sidebar: false
extra_css: [extra.css]
google_analytics: ['UA-99756181-1', 'billpowellisalive.com']
remote_branch: master
